-
    name: 'Execute a command to display hosts file on localhost'
    hosts: all
    tasks:
        -
            name: 'Execute a command to display hosts file'
            command: 'cat /etc/hosts'
